### ISSUE TITLE
DB Error on Install

### ISSUE THREAD

**Issue by JeBuSBrian** [JMAConsulting/biz.jmaconsulting.attentively#48]
I attempted to install this to CiviCRM 4.6.1 and it resulted in an error message DB Error. Database tables were added, menu items were added. But the menu item pointed to the CiviCRM dashboard. Doesn't seem like it works.

**Comment by pradpnayak** [comment]
HiCould you please provide us with a error message what you got during installing the extension?The current version of attentive.ly beta supports for 4.5 and 4.4 version of CiviCRM. We are in a process of releasing a 4.6 version of it.                                                                                                                                     Sent from my BlackBerry 10 smartphone.

**Comment by pradpnayak** [comment]
Hi @JeBuSBrian 

If you getting DB:error for civicrm_option_value table then could you please pull latest code from master branch and check if the error still persist?

or you can apply PR for db error at https://github.com/JMAConsulting/biz.jmaconsulting.attentively/pull/49

HTH
Pradeep
